apiVersion: v1
kind: Pod
metadata:
  name: dnstools
  namespace: default
spec:
  hostname: dns
  subdomain: tools
  containers:
    - name: dnstools
      image: infoblox/dnstools:latest
      command:
        - sleep
        - "36000"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always